#version: '3'
#services:
#  header-app:
#    image: adesh3721/mini-project/:1.0.0
#    container_name: header-app
#    ports:
#      - "8080:8080"

version: '3'
services:
  hospital-app:
    image: adesh3721/hospital-management-app:1.0.0
    ports:
      - "8080:8080"
    environment:
      spring.data.mongodb.uri: mongodb://mongo:27017/data
    depends_on:
      - mongo
    networks:
      - hospital-network
  mongo:
    image: mongo:3.4.7
    ports:
      - "27017:27017"
    networks:
      - hospital-network
networks:
  hospital-network:
    driver: bridge